### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by ghost** [316k/DopeWars.js#2]
Title says it all.

Usefull link: https://hacks.mozilla.org/2013/08/localizing-firefox-os-apps/

**Comment by 316k** [comment]
Thanks for the link ! I wanted to localize it but I had problems finding 
javascript libraries to do it. I'm currently working on an update. If 
you have any other idea for the game, feel free to contact me !

Nicolas

**Comment by 316k** [comment]
Done !
You can create additionnal locales/*.properties files and add them in locales/locales.ini to translate it in  more languages.
